Repository let-s-record-it/Server, pull requests merged in 2024-06, with the labels that each got.

#84 Refactor 64: 월 목표 도메인 리팩토링
  src/main/java/com/sillim/recordit/global/advice/common/GlobalControllerAdvice.java
  src/main/java/com/sillim/recordit/global/util/LoggingUtils.java
  src/main/java/com/sillim/recordit/global/validation/goal/ValidDescription.java
  src/main/java/com/sillim/recordit/global/validation/goal/ValidMonth.java
  src/main/java/com/sillim/recordit/global/validation/goal/ValidTitle.java
  src/main/java/com/sillim/recordit/global/validation/goal/ValidYear.java
  src/main/java/com/sillim/recordit/global/validation/goal/YearValidator.java
  src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
  src/main/java/com/sillim/recordit/goal/controller/dto/request/MonthlyGoalUpdateRequest.java
  src/main/java/com/sillim/recordit/goal/domain/MonthlyGoal.java
  src/main/java/com/sillim/recordit/goal/domain/vo/GoalColorHex.java
  src/main/java/com/sillim/recordit/goal/domain/vo/GoalDescription.java
  src/main/java/com/sillim/recordit/goal/domain/vo/GoalPeriod.java
  src/main/java/com/sillim/recordit/goal/domain/vo/GoalTitle.java
  src/main/java/com/sillim/recordit/goal/dto/request/MonthlyGoalUpdateRequest.java
  src/main/java/com/sillim/recordit/goal/dto/response/MonthlyGoalDetailsResponse.java
  src/main/java/com/sillim/recordit/goal/dto/response/MonthlyGoalListResponse.java
  src/main/java/com/sillim/recordit/goal/repository/CustomMonthlyGoalRepository.java
  src/main/java/com/sillim/recordit/goal/repository/CustomMonthlyGoalRepositoryImpl.java
  src/main/java/com/sillim/recordit/goal/repository/MonthlyGoalRepository.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalQueryService.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
  src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/dto/request/MonthlyUpdateRequestTest.java
  src/test/java/com/sillim/recordit/goal/repository/MonthlyGoalRepositoryTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalQueryServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
  src/test/java/com/sillim/recordit/validation/YearValidatorTest.java
Labels: refactor

#90 Feature 55: 월 목표 삭제 기능 구현
  src/docs/asciidoc/monthly-goal.adoc
  src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
  src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
Labels: feature, test

#89 Release goal
  src/docs/asciidoc/monthly-goal.adoc
  src/main/java/com/sillim/recordit/global/advice/common/GlobalControllerAdvice.java
  src/main/java/com/sillim/recordit/global/util/LoggingUtils.java
  src/main/java/com/sillim/recordit/global/validation/goal/ValidDescription.java
  src/main/java/com/sillim/recordit/global/validation/goal/ValidMonth.java
  src/main/java/com/sillim/recordit/global/validation/goal/ValidTitle.java
  src/main/java/com/sillim/recordit/global/validation/goal/ValidYear.java
  src/main/java/com/sillim/recordit/global/validation/goal/YearValidator.java
  src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
  src/main/java/com/sillim/recordit/goal/controller/dto/request/MonthlyGoalUpdateRequest.java
  src/main/java/com/sillim/recordit/goal/domain/MonthlyGoal.java
  src/main/java/com/sillim/recordit/goal/dto/request/MonthlyGoalUpdateRequest.java
  src/main/java/com/sillim/recordit/goal/dto/response/MonthlyGoalDetailsResponse.java
  src/main/java/com/sillim/recordit/goal/dto/response/MonthlyGoalListResponse.java
  src/main/java/com/sillim/recordit/goal/repository/CustomMonthlyGoalRepository.java
  src/main/java/com/sillim/recordit/goal/repository/CustomMonthlyGoalRepositoryImpl.java
  src/main/java/com/sillim/recordit/goal/repository/MonthlyGoalRepository.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalQueryService.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
  src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/dto/request/MonthlyUpdateRequestTest.java
  src/test/java/com/sillim/recordit/goal/repository/MonthlyGoalRepositoryTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalQueryServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
  src/test/java/com/sillim/recordit/validation/YearValidatorTest.java
Labels: feature

#94 일간 일정 조회 기능 구현
  src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
  src/main/java/com/sillim/recordit/schedule/domain/RepetitionPattern.java
  src/main/java/com/sillim/recordit/schedule/domain/ScheduleGroup.java
  src/main/java/com/sillim/recordit/schedule/domain/vo/MonthOfYear.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
  src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
Labels: feature

#95 Release schedule
  src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
  src/main/java/com/sillim/recordit/schedule/domain/RepetitionPattern.java
  src/main/java/com/sillim/recordit/schedule/domain/ScheduleGroup.java
  src/main/java/com/sillim/recordit/schedule/domain/vo/MonthOfYear.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
  src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
Labels: feature

#97 🚑️ hotfix[#96]: 반복 일정이 없을 경우 NPE가 발생하는 현상 수정
  src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
  src/main/java/com/sillim/recordit/schedule/domain/ScheduleGroup.java
Labels: hotfix

#98 🚑️ hotfix[#96]: setLocation 필드가 null로 반환되는 현상 수정
  src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
Labels: hotfix

#100 일별 일정 반환 필드 추가
  src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
  src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
Labels: feature

#101 Release schedule
  src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
  src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
Labels: feature

#103 🚑️ hotfix[#102]: Schedule에서 Calendar 조회 시 컨텍스트 외부 조회 에러 문제 해결
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
Labels: hotfix

#104 Feature 91: 할 일 추가 기능 구현
  src/docs/asciidoc/task.adoc
  src/main/java/com/sillim/recordit/calendar/repository/CalendarRepository.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarService.java
  src/main/java/com/sillim/recordit/enums/date/Weekday.java
  src/main/java/com/sillim/recordit/global/advice/common/GlobalControllerAdvice.java
  src/main/java/com/sillim/recordit/global/advice/goal/GoalControllerAdvice.java
  src/main/java/com/sillim/recordit/global/advice/task/TaskControllerAdvice.java
  src/main/java/com/sillim/recordit/global/exception/common/DayOfMonthOutOfRangeException.java
  src/main/java/com/sillim/recordit/global/util/DateTimeUtils.java
  src/main/java/com/sillim/recordit/global/validation/goal/ValidDescription.java
  src/main/java/com/sillim/recordit/global/validation/goal/ValidTitle.java
  src/main/java/com/sillim/recordit/global/validation/task/ValidDayOfMonth.java
  src/main/java/com/sillim/recordit/global/validation/task/ValidMonth.java
  src/main/java/com/sillim/recordit/global/validation/task/ValidWeekdayBit.java
  src/main/java/com/sillim/recordit/goal/domain/vo/GoalDescription.java
  src/main/java/com/sillim/recordit/goal/domain/vo/WeeklyGoalPeriod.java
  src/main/java/com/sillim/recordit/goal/dto/request/MonthlyGoalUpdateRequest.java
  src/main/java/com/sillim/recordit/task/controller/TaskController.java
  src/main/java/com/sillim/recordit/task/domain/Task.java
  src/main/java/com/sillim/recordit/task/domain/TaskGroup.java
  src/main/java/com/sillim/recordit/task/domain/repetition/TaskYearlyRepetitionPattern.java
  src/main/java/com/sillim/recordit/task/domain/vo/TaskDescription.java
  src/main/java/com/sillim/recordit/task/dto/TaskAddRequest.java
  src/main/java/com/sillim/recordit/task/dto/TaskRepetitionAddRequest.java
  src/main/java/com/sillim/recordit/task/repository/TaskGroupRepository.java
  src/main/java/com/sillim/recordit/task/repository/TaskRepetitionPatternRepository.java
  src/main/java/com/sillim/recordit/task/repository/TaskRepository.java
  src/main/java/com/sillim/recordit/task/service/TaskCommandService.java
  src/main/java/com/sillim/recordit/task/service/TaskGroupService.java
  src/main/java/com/sillim/recordit/task/service/TaskRepetitionPatternService.java
  src/test/java/com/sillim/recordit/global/util/DateTimeUtilsTest.java
  src/test/java/com/sillim/recordit/goal/domain/vo/GoalDescriptionTest.java
  src/test/java/com/sillim/recordit/goal/domain/vo/MonthlyGoalPeriodTest.java
  src/test/java/com/sillim/recordit/goal/domain/vo/WeeklyGoalPeriodTest.java
  src/test/java/com/sillim/recordit/task/controller/TaskControllerTest.java
  src/test/java/com/sillim/recordit/task/domain/vo/TaskDescriptionTest.java
  src/test/java/com/sillim/recordit/task/fixture/TaskFixture.java
  src/test/java/com/sillim/recordit/task/fixture/TaskRepetitionPatternFixture.java
  src/test/java/com/sillim/recordit/task/repository/TaskRepetitionPatternRepositoryTest.java
  src/test/java/com/sillim/recordit/task/repository/TaskRepositoryTest.java
  src/test/java/com/sillim/recordit/task/service/TaskCommandServiceTest.java
  src/test/java/com/sillim/recordit/task/service/TaskGroupServiceTest.java
  src/test/java/com/sillim/recordit/task/service/TaskRepetitionPatternServiceTest.java
Labels: feature, test
