Repository let-s-record-it/Server, pull requests merged in 2024-07, with the labels that each got.

#110 Feature 108 일정 알람 1:N 관계로 추출
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/exception/common/InvalidRequestException.java
  src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
  src/main/java/com/sillim/recordit/schedule/domain/RepetitionPattern.java
  src/main/java/com/sillim/recordit/schedule/domain/Schedule.java
  src/main/java/com/sillim/recordit/schedule/domain/ScheduleAlarm.java
  src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
  src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
  src/main/java/com/sillim/recordit/schedule/repository/ScheduleAlarmRepository.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleAlarmService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
  src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/sillim/recordit/schedule/domain/ScheduleTest.java
  src/test/java/com/sillim/recordit/schedule/fixture/ScheduleFixture.java
  src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
Labels: feature, refactor

#115 Release schedule
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/exception/common/InvalidRequestException.java
  src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
  src/main/java/com/sillim/recordit/schedule/domain/RepetitionPattern.java
  src/main/java/com/sillim/recordit/schedule/domain/Schedule.java
  src/main/java/com/sillim/recordit/schedule/domain/ScheduleAlarm.java
  src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
  src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
  src/main/java/com/sillim/recordit/schedule/repository/ScheduleAlarmRepository.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleAlarmService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
  src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/sillim/recordit/schedule/domain/ScheduleTest.java
  src/test/java/com/sillim/recordit/schedule/fixture/ScheduleFixture.java
  src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
Labels: feature

#112 Feature 111: 할 일 상세조회 기능 구현 및 테스트
  src/docs/asciidoc/task.adoc
  src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalQueryService.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
  src/main/java/com/sillim/recordit/task/controller/TaskController.java
  src/main/java/com/sillim/recordit/task/domain/Task.java
  src/main/java/com/sillim/recordit/task/domain/TaskGroup.java
  src/main/java/com/sillim/recordit/task/domain/repetition/TaskRepetitionPattern.java
  src/main/java/com/sillim/recordit/task/domain/repetition/TaskWeeklyRepetitionPattern.java
  src/main/java/com/sillim/recordit/task/domain/vo/TaskWeekdayBit.java
  src/main/java/com/sillim/recordit/task/dto/response/RelatedGoalDetailsResponse.java
  src/main/java/com/sillim/recordit/task/dto/response/TaskDetailsResponse.java
  src/main/java/com/sillim/recordit/task/dto/response/TaskRepetitionDetailsResponse.java
  src/main/java/com/sillim/recordit/task/repository/TaskRepetitionPatternRepository.java
  src/main/java/com/sillim/recordit/task/repository/TaskRepository.java
  src/main/java/com/sillim/recordit/task/service/TaskGroupService.java
  src/main/java/com/sillim/recordit/task/service/TaskQueryService.java
  src/main/java/com/sillim/recordit/task/service/TaskRepetitionPatternService.java
  src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalQueryServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
  src/test/java/com/sillim/recordit/task/controller/TaskControllerTest.java
  src/test/java/com/sillim/recordit/task/domain/TaskTest.java
  src/test/java/com/sillim/recordit/task/domain/repetition/TaskWeeklyRepetitionPatternTest.java
  src/test/java/com/sillim/recordit/task/domain/vo/TaskWeekdayBitTest.java
  src/test/java/com/sillim/recordit/task/repository/TaskRepositoryTest.java
  src/test/java/com/sillim/recordit/task/service/TaskGroupServiceTest.java
  src/test/java/com/sillim/recordit/task/service/TaskQueryServiceTest.java
Labels: feature, test

#118 Fix 114: 할 일 도메인 API 연동 중 발생한 오류 수정, 테스트 코드 리팩토링
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalQueryService.java
  src/main/java/com/sillim/recordit/task/domain/repetition/TaskMonthlyRepetitionPattern.java
  src/main/java/com/sillim/recordit/task/domain/repetition/TaskRepetitionPattern.java
  src/main/java/com/sillim/recordit/task/domain/repetition/TaskYearlyRepetitionPattern.java
  src/main/java/com/sillim/recordit/task/dto/response/TaskRepetitionDetailsResponse.java
  src/main/java/com/sillim/recordit/task/service/TaskGroupService.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalQueryServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
  src/test/java/com/sillim/recordit/task/service/TaskCommandServiceTest.java
  src/test/java/com/sillim/recordit/task/service/TaskGroupServiceTest.java
  src/test/java/com/sillim/recordit/task/service/TaskQueryServiceTest.java
Labels: fix

#109 Feature 106: 할 일 목록 조회 기능 구현
  src/docs/asciidoc/task.adoc
  src/main/java/com/sillim/recordit/calendar/repository/CalendarRepository.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarService.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/exception/goal/InvalidMonthlyGoalException.java
  src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
  src/main/java/com/sillim/recordit/goal/domain/MonthlyGoal.java
  src/main/java/com/sillim/recordit/goal/domain/WeeklyGoal.java
  src/main/java/com/sillim/recordit/goal/repository/CustomMonthlyGoalRepository.java
  src/main/java/com/sillim/recordit/goal/repository/CustomMonthlyGoalRepositoryImpl.java
  src/main/java/com/sillim/recordit/goal/repository/MonthlyGoalRepository.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalQueryService.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
  src/main/java/com/sillim/recordit/task/controller/TaskController.java
  src/main/java/com/sillim/recordit/task/domain/Task.java
  src/main/java/com/sillim/recordit/task/domain/TaskGroup.java
  src/main/java/com/sillim/recordit/task/domain/repetition/TaskMonthlyRepetitionPattern.java
  src/main/java/com/sillim/recordit/task/domain/repetition/TaskRepetitionPattern.java
  src/main/java/com/sillim/recordit/task/domain/repetition/TaskWeeklyRepetitionPattern.java
  src/main/java/com/sillim/recordit/task/domain/repetition/TaskYearlyRepetitionPattern.java
  src/main/java/com/sillim/recordit/task/domain/vo/TaskWeekdayBit.java
  src/main/java/com/sillim/recordit/task/dto/request/TaskAddRequest.java
  src/main/java/com/sillim/recordit/task/dto/request/TaskRepetitionAddRequest.java
  src/main/java/com/sillim/recordit/task/dto/response/RelatedGoalDetailsResponse.java
  src/main/java/com/sillim/recordit/task/dto/response/TaskDetailsResponse.java
  src/main/java/com/sillim/recordit/task/dto/response/TaskRepetitionDetailsResponse.java
  src/main/java/com/sillim/recordit/task/dto/response/TaskResponse.java
  src/main/java/com/sillim/recordit/task/repository/TaskRepetitionPatternRepository.java
  src/main/java/com/sillim/recordit/task/repository/TaskRepository.java
  src/main/java/com/sillim/recordit/task/service/TaskCommandService.java
  src/main/java/com/sillim/recordit/task/service/TaskGroupService.java
  src/main/java/com/sillim/recordit/task/service/TaskQueryService.java
  src/main/java/com/sillim/recordit/task/service/TaskRepetitionPatternService.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarServiceTest.java
  src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/repository/MonthlyGoalRepositoryTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalQueryServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
  src/test/java/com/sillim/recordit/task/controller/TaskControllerTest.java
  src/test/java/com/sillim/recordit/task/domain/TaskTest.java
  src/test/java/com/sillim/recordit/task/domain/repetition/TaskWeeklyRepetitionPatternTest.java
  src/test/java/com/sillim/recordit/task/domain/vo/TaskWeekdayBitTest.java
  src/test/java/com/sillim/recordit/task/fixture/TaskFixture.java
  src/test/java/com/sillim/recordit/task/repository/TaskRepositoryTest.java
  src/test/java/com/sillim/recordit/task/service/TaskCommandServiceTest.java
  src/test/java/com/sillim/recordit/task/service/TaskGroupServiceTest.java
  src/test/java/com/sillim/recordit/task/service/TaskQueryServiceTest.java
  src/test/java/com/sillim/recordit/task/service/TaskRepetitionPatternServiceTest.java
Labels: feature, test

#117 Feature 116 일정 삭제 기능 구현
  src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
  src/main/java/com/sillim/recordit/schedule/domain/Schedule.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
  src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
Labels: feature

#121 Release schedule
  src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
  src/main/java/com/sillim/recordit/schedule/domain/Schedule.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
  src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
Labels: feature

#123 🚑️ hotfix[#122]: alarmTimes field가 null로 반환되는 현상 수정
  src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
Labels: hotfix

#125 Fix 120: 월 목표 도메인 API 연동 중 발생한 수정사항 반영
  src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
Labels: fix

#129 ✨ feature[#128]: DayScheduleResponse에 CalendarId 필드 추가
  src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
Labels: feature

#130 Release schedule
  src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
Labels: feature

#133 🚑️ hotfix[#132]: ScheduleAlarms orphanRemoval 에러 수정
  src/main/java/com/sillim/recordit/schedule/domain/Schedule.java
Labels: hotfix

#135 🚑️ hotfix[#134]: scheduleGroup -> repetitionPattern cascade Persist 누락
  src/main/java/com/sillim/recordit/schedule/domain/ScheduleGroup.java
Labels: hotfix

#137 🚑️ hotfix[#136]: RepetitionPattern 생성으로 인한 unique constraint 에러 수정
  src/main/java/com/sillim/recordit/schedule/domain/RepetitionPattern.java
  src/main/java/com/sillim/recordit/schedule/domain/ScheduleGroup.java
Labels: hotfix

#139 🚑️ hotfix[#138]: 그룹 일정에서 반복 해제 시 일정이 삭제되는 현상 수정
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
Labels: hotfix

#141 Feature 140 피드 생성 기능 구현
  src/main/java/com/sillim/recordit/feed/controller/FeedController.java
  src/main/java/com/sillim/recordit/feed/domain/Feed.java
  src/main/java/com/sillim/recordit/feed/domain/FeedImage.java
  src/main/java/com/sillim/recordit/feed/domain/vo/FeedContent.java
  src/main/java/com/sillim/recordit/feed/domain/vo/FeedImageUrl.java
  src/main/java/com/sillim/recordit/feed/domain/vo/FeedImages.java
  src/main/java/com/sillim/recordit/feed/domain/vo/FeedTitle.java
  src/main/java/com/sillim/recordit/feed/dto/request/FeedAddRequest.java
  src/main/java/com/sillim/recordit/feed/repository/FeedRepository.java
  src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
  src/main/java/com/sillim/recordit/global/advice/feed/FeedControllerAdvice.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedContentException.java
  src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedImageCountException.java
  src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedImageUrlException.java
  src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
  src/test/java/com/sillim/recordit/feed/domain/FeedImageTest.java
  src/test/java/com/sillim/recordit/feed/domain/FeedTest.java
  src/test/java/com/sillim/recordit/feed/domain/vo/FeedContentTest.java
  src/test/java/com/sillim/recordit/feed/domain/vo/FeedImageUrlTest.java
  src/test/java/com/sillim/recordit/feed/domain/vo/FeedImagesTest.java
  src/test/java/com/sillim/recordit/feed/domain/vo/FeedTitleTest.java
  src/test/java/com/sillim/recordit/feed/fixture/FeedFixture.java
  src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
Labels: feature

#144 Release feed
  src/main/java/com/sillim/recordit/feed/controller/FeedController.java
  src/main/java/com/sillim/recordit/feed/domain/Feed.java
  src/main/java/com/sillim/recordit/feed/domain/FeedImage.java
  src/main/java/com/sillim/recordit/feed/domain/vo/FeedContent.java
  src/main/java/com/sillim/recordit/feed/domain/vo/FeedImageUrl.java
  src/main/java/com/sillim/recordit/feed/domain/vo/FeedImages.java
  src/main/java/com/sillim/recordit/feed/domain/vo/FeedTitle.java
  src/main/java/com/sillim/recordit/feed/dto/request/FeedAddRequest.java
  src/main/java/com/sillim/recordit/feed/repository/FeedRepository.java
  src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
  src/main/java/com/sillim/recordit/global/advice/feed/FeedControllerAdvice.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedContentException.java
  src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedImageCountException.java
  src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedImageUrlException.java
  src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
  src/test/java/com/sillim/recordit/feed/domain/FeedImageTest.java
  src/test/java/com/sillim/recordit/feed/domain/FeedTest.java
  src/test/java/com/sillim/recordit/feed/domain/vo/FeedContentTest.java
  src/test/java/com/sillim/recordit/feed/domain/vo/FeedImageUrlTest.java
  src/test/java/com/sillim/recordit/feed/domain/vo/FeedImagesTest.java
  src/test/java/com/sillim/recordit/feed/domain/vo/FeedTitleTest.java
  src/test/java/com/sillim/recordit/feed/fixture/FeedFixture.java
  src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
Labels: feature

#143 Feature 142: 할 일 그룹 내 이후 할 일 전체 수정 기능 구현
  src/docs/asciidoc/task.adoc
  src/main/java/com/sillim/recordit/task/controller/TaskController.java
  src/main/java/com/sillim/recordit/task/repository/CustomTaskRepository.java
  src/main/java/com/sillim/recordit/task/repository/CustomTaskRepositoryImpl.java
  src/main/java/com/sillim/recordit/task/repository/TaskRepository.java
  src/main/java/com/sillim/recordit/task/service/TaskCommandService.java
  src/test/java/com/sillim/recordit/task/controller/TaskControllerTest.java
  src/test/java/com/sillim/recordit/task/repository/CustomTaskRepositoryTest.java
  src/test/java/com/sillim/recordit/task/repository/TaskRepositoryTest.java
  src/test/java/com/sillim/recordit/task/service/TaskCommandServiceTest.java
Labels: feature

#150 Feature 149 피드 상세 조회 기능 구현
  docker-compose.yml
  src/main/java/com/sillim/recordit/feed/controller/FeedController.java
  src/main/java/com/sillim/recordit/feed/domain/Feed.java
  src/main/java/com/sillim/recordit/feed/dto/response/FeedDetailsResponse.java
  src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepository.java
  src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryImpl.java
  src/main/java/com/sillim/recordit/feed/repository/FeedRepository.java
  src/main/java/com/sillim/recordit/feed/service/FeedImageUploadService.java
  src/main/java/com/sillim/recordit/feed/service/FeedQueryService.java
  src/main/java/com/sillim/recordit/global/util/FileUtils.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
  src/test/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryTest.java
  src/test/java/com/sillim/recordit/feed/repository/FeedRepositoryTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedImageUploadServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedQueryServiceTest.java
  src/test/java/com/sillim/recordit/global/util/FileUtilsTest.java
  src/test/resources/application-test.yml
Labels: feature

#151 Release feed
  docker-compose.yml
  src/main/java/com/sillim/recordit/feed/controller/FeedController.java
  src/main/java/com/sillim/recordit/feed/domain/Feed.java
  src/main/java/com/sillim/recordit/feed/dto/response/FeedDetailsResponse.java
  src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepository.java
  src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryImpl.java
  src/main/java/com/sillim/recordit/feed/repository/FeedRepository.java
  src/main/java/com/sillim/recordit/feed/service/FeedImageUploadService.java
  src/main/java/com/sillim/recordit/feed/service/FeedQueryService.java
  src/main/java/com/sillim/recordit/global/util/FileUtils.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
  src/test/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryTest.java
  src/test/java/com/sillim/recordit/feed/repository/FeedRepositoryTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedImageUploadServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedQueryServiceTest.java
  src/test/java/com/sillim/recordit/global/util/FileUtilsTest.java
  src/test/resources/application-test.yml
Labels: feature

#153 Feature 152 피드 목록 조회 기능 구현
  src/main/java/com/sillim/recordit/feed/controller/FeedController.java
  src/main/java/com/sillim/recordit/feed/domain/vo/FeedImages.java
  src/main/java/com/sillim/recordit/feed/dto/response/FeedInListResponse.java
  src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepository.java
  src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryImpl.java
  src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
  src/main/java/com/sillim/recordit/feed/service/FeedQueryService.java
  src/main/java/com/sillim/recordit/global/dto/response/SliceResponse.java
  src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
  src/test/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedQueryServiceTest.java
Labels: feature

#154 Release feed
  src/main/java/com/sillim/recordit/feed/controller/FeedController.java
  src/main/java/com/sillim/recordit/feed/domain/vo/FeedImages.java
  src/main/java/com/sillim/recordit/feed/dto/response/FeedInListResponse.java
  src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepository.java
  src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryImpl.java
  src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
  src/main/java/com/sillim/recordit/feed/service/FeedQueryService.java
  src/main/java/com/sillim/recordit/global/dto/response/SliceResponse.java
  src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
  src/test/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedQueryServiceTest.java
Labels: feature

#156 Feature 155 피드 좋아요/스크랩 기능 구현
  src/main/java/com/sillim/recordit/feed/controller/FeedController.java
  src/main/java/com/sillim/recordit/feed/domain/Feed.java
  src/main/java/com/sillim/recordit/feed/domain/FeedLike.java
  src/main/java/com/sillim/recordit/feed/domain/FeedScrap.java
  src/main/java/com/sillim/recordit/feed/dto/response/FeedDetailsResponse.java
  src/main/java/com/sillim/recordit/feed/dto/response/FeedInListResponse.java
  src/main/java/com/sillim/recordit/feed/repository/FeedLikeRepository.java
  src/main/java/com/sillim/recordit/feed/repository/FeedScrapRepository.java
  src/main/java/com/sillim/recordit/feed/service/FeedLikeQueryService.java
  src/main/java/com/sillim/recordit/feed/service/FeedLikeService.java
  src/main/java/com/sillim/recordit/feed/service/FeedQueryService.java
  src/main/java/com/sillim/recordit/feed/service/FeedScrapQueryService.java
  src/main/java/com/sillim/recordit/feed/service/FeedScrapService.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedLikeException.java
  src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
  src/test/java/com/sillim/recordit/feed/domain/FeedTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedLikeQueryServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedLikeServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedQueryServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedScrapQueryServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedScrapServiceTest.java
Labels: feature

#157 Release feed
  src/main/java/com/sillim/recordit/feed/controller/FeedController.java
  src/main/java/com/sillim/recordit/feed/domain/Feed.java
  src/main/java/com/sillim/recordit/feed/domain/FeedLike.java
  src/main/java/com/sillim/recordit/feed/domain/FeedScrap.java
  src/main/java/com/sillim/recordit/feed/dto/response/FeedDetailsResponse.java
  src/main/java/com/sillim/recordit/feed/dto/response/FeedInListResponse.java
  src/main/java/com/sillim/recordit/feed/repository/FeedLikeRepository.java
  src/main/java/com/sillim/recordit/feed/repository/FeedScrapRepository.java
  src/main/java/com/sillim/recordit/feed/service/FeedLikeQueryService.java
  src/main/java/com/sillim/recordit/feed/service/FeedLikeService.java
  src/main/java/com/sillim/recordit/feed/service/FeedQueryService.java
  src/main/java/com/sillim/recordit/feed/service/FeedScrapQueryService.java
  src/main/java/com/sillim/recordit/feed/service/FeedScrapService.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedLikeException.java
  src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
  src/test/java/com/sillim/recordit/feed/domain/FeedTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedLikeQueryServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedLikeServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedQueryServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedScrapQueryServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedScrapServiceTest.java
Labels: feature

#161 Release feed
  src/main/java/com/sillim/recordit/feed/controller/FeedController.java
  src/main/java/com/sillim/recordit/feed/domain/Feed.java
  src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryImpl.java
  src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
  src/test/java/com/sillim/recordit/feed/controller/FeedControllerTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
Labels: feature

#162 Feature 159 피드 수정 기능 구현
  src/main/java/com/sillim/recordit/feed/controller/FeedController.java
  src/main/java/com/sillim/recordit/feed/domain/Feed.java
  src/main/java/com/sillim/recordit/feed/domain/vo/FeedImages.java
  src/main/java/com/sillim/recordit/feed/dto/request/FeedModifyRequest.java
  src/main/java/com/sillim/recordit/feed/service/FeedCommandService.java
  src/main/java/com/sillim/recordit/feed/service/FeedImageUploadService.java
  src/test/java/com/sillim/recordit/feed/domain/FeedTest.java
  src/test/java/com/sillim/recordit/feed/domain/vo/FeedImagesTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedCommandServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedImageUploadServiceTest.java
Labels: feature

#166 Feature 165 피드 댓글 생성 기능 구현
  src/main/java/com/sillim/recordit/feed/controller/FeedCommentController.java
  src/main/java/com/sillim/recordit/feed/domain/FeedComment.java
  src/main/java/com/sillim/recordit/feed/domain/vo/FeedCommentContent.java
  src/main/java/com/sillim/recordit/feed/dto/request/FeedCommentAddRequest.java
  src/main/java/com/sillim/recordit/feed/repository/FeedCommentRepository.java
  src/main/java/com/sillim/recordit/feed/service/FeedCommentCommandService.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/exception/feed/InvalidFeedCommentContentException.java
  src/test/java/com/sillim/recordit/feed/controller/FeedCommentControllerTest.java
  src/test/java/com/sillim/recordit/feed/domain/FeedCommentTest.java
  src/test/java/com/sillim/recordit/feed/domain/vo/FeedCommentContentTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedCommentCommandServiceTest.java
Labels: feature

#168 Feature 167 피드 댓글 조회 기능 구현
  src/main/java/com/sillim/recordit/feed/controller/FeedCommentController.java
  src/main/java/com/sillim/recordit/feed/domain/FeedComment.java
  src/main/java/com/sillim/recordit/feed/dto/response/FeedCommentInListResponse.java
  src/main/java/com/sillim/recordit/feed/repository/CustomFeedCommentRepository.java
  src/main/java/com/sillim/recordit/feed/repository/CustomFeedCommentRepositoryImpl.java
  src/main/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryImpl.java
  src/main/java/com/sillim/recordit/feed/repository/FeedCommentRepository.java
  src/main/java/com/sillim/recordit/feed/service/FeedCommentQueryService.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/querydsl/QuerydslRepositorySupport.java
  src/test/java/com/sillim/recordit/feed/controller/FeedCommentControllerTest.java
  src/test/java/com/sillim/recordit/feed/domain/FeedCommentTest.java
  src/test/java/com/sillim/recordit/feed/domain/vo/FeedCommentContentTest.java
  src/test/java/com/sillim/recordit/feed/repository/CustomFeedCommentRepositoryTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedCommentCommandServiceTest.java
  src/test/java/com/sillim/recordit/feed/service/FeedCommentQueryServiceTest.java
Labels: feature
