Repository let-s-record-it/Server, pull requests merged in 2024-04, with the labels that each got.

#21 [Chore] 이슈 템플릿 title 수정
  .github/ISSUE_TEMPLATE/🐞bug.md
  .github/ISSUE_TEMPLATE/🛠️feature.md
Labels: docs

#23 [Hotfix] RestDocs 누락된 설정 추가
  build.gradle
Labels: hotfix

#12 [Feature] 월 목표 추가 API 구현 및 테스트
  src/docs/asciidoc/monthly-goal.adoc
  src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
  src/main/java/com/sillim/recordit/goal/controller/dto/request/MonthlyGoalAddRequest.java
  src/main/java/com/sillim/recordit/goal/domain/Member.java
  src/main/java/com/sillim/recordit/goal/domain/MonthlyGoal.java
  src/main/java/com/sillim/recordit/goal/repository/MonthlyGoalJpaRepository.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
  src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/controller/dto/request/MonthlyAddRequestTest.java
  src/test/java/com/sillim/recordit/goal/fixture/MonthlyGoalFixture.java
  src/test/java/com/sillim/recordit/goal/repository/MonthlyGoalJpaRepositoryTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
Labels: feature

#30 [Hotfix] EntityNotFoundException 추가
  src/main/java/com/sillim/recordit/global/advice/common/GlobalControllerAdvice.java
  src/main/java/com/sillim/recordit/global/exception/common/RecordNotFoundException.java
Labels: hotfix

#31 [Feature] 월 목표 수정 API 구현 및 단위 테스트
  src/docs/asciidoc/monthly-goal.adoc
  src/main/java/com/sillim/recordit/global/advice/common/GlobalControllerAdvice.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/exception/common/ApplicationException.java
  src/main/java/com/sillim/recordit/global/exception/common/RecordNotFoundException.java
  src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
  src/main/java/com/sillim/recordit/goal/controller/dto/request/MonthlyGoalUpdateRequest.java
  src/main/java/com/sillim/recordit/goal/domain/MonthlyGoal.java
  src/main/java/com/sillim/recordit/goal/repository/MemberJpaRepository.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalQueryService.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
  src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/controller/dto/request/MonthlyUpdateRequestTest.java
  src/test/java/com/sillim/recordit/goal/fixture/MonthlyGoalFixture.java
  src/test/java/com/sillim/recordit/goal/repository/MonthlyGoalJpaRepositoryTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalQueryServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
Labels: feature, test

#33 [Feature] 월 목표 목록 조회 API 구현 및 단위 테스트
  src/docs/asciidoc/monthly-goal.adoc
  src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
  src/main/java/com/sillim/recordit/goal/controller/dto/response/MonthlyGoalListResponse.java
  src/main/java/com/sillim/recordit/goal/repository/MemberJpaRepository.java
  src/main/java/com/sillim/recordit/goal/repository/MonthlyGoalJpaRepository.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalQueryService.java
  src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/fixture/MonthlyGoalFixture.java
  src/test/java/com/sillim/recordit/goal/repository/MonthlyGoalJpaRepositoryTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalQueryServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
Labels: feature, test

#40 [Fix] 월 목표 조회 조건에 deleted 컬럼 포함
  src/main/java/com/sillim/recordit/goal/domain/MonthlyGoal.java
  src/test/java/com/sillim/recordit/goal/controller/dto/request/MonthlyUpdateRequestTest.java
Labels: fix

#43 chore: Create codereview.yml
  .github/workflows/codereview.yml
Labels: chore
