Repository let-s-record-it/Server, pull requests merged in 2024-05, with the labels that each got.

#49 Release Goal: 월 목표 추가, 수정, 목록 조회, 상세 조회 기능 구현
  src/docs/asciidoc/monthly-goal.adoc
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
  src/main/java/com/sillim/recordit/goal/controller/dto/request/MonthlyGoalUpdateRequest.java
  src/main/java/com/sillim/recordit/goal/controller/dto/response/MonthlyGoalDetailsResponse.java
  src/main/java/com/sillim/recordit/goal/controller/dto/response/MonthlyGoalListResponse.java
  src/main/java/com/sillim/recordit/goal/domain/MonthlyGoal.java
  src/main/java/com/sillim/recordit/goal/repository/MonthlyGoalJpaRepository.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalQueryService.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
  src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/controller/dto/request/MonthlyUpdateRequestTest.java
  src/test/java/com/sillim/recordit/goal/fixture/MonthlyGoalFixture.java
  src/test/java/com/sillim/recordit/goal/repository/MonthlyGoalJpaRepositoryTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalQueryServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
  src/test/java/com/sillim/recordit/support/restdocs/RestDocsTest.java
Labels: feature

#58 ✨ feature[#37]: 일정 상세 조회 기능 구현
  src/main/java/com/sillim/recordit/calendar/domain/vo/CalendarTitle.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
  src/main/java/com/sillim/recordit/schedule/domain/RepetitionPattern.java
  src/main/java/com/sillim/recordit/schedule/domain/Schedule.java
  src/main/java/com/sillim/recordit/schedule/domain/ScheduleGroup.java
  src/main/java/com/sillim/recordit/schedule/domain/WeekNumber.java
  src/main/java/com/sillim/recordit/schedule/domain/Weekday.java
  src/main/java/com/sillim/recordit/schedule/domain/vo/Location.java
  src/main/java/com/sillim/recordit/schedule/domain/vo/MonthOfYear.java
  src/main/java/com/sillim/recordit/schedule/domain/vo/ScheduleDescription.java
  src/main/java/com/sillim/recordit/schedule/domain/vo/ScheduleTitle.java
  src/main/java/com/sillim/recordit/schedule/domain/vo/WeekdayBit.java
  src/main/java/com/sillim/recordit/schedule/dto/request/RepetitionAddRequest.java
  src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
  src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
  src/main/java/com/sillim/recordit/schedule/dto/response/MonthScheduleResponse.java
  src/main/java/com/sillim/recordit/schedule/dto/response/RepeatedWeekday.java
  src/main/java/com/sillim/recordit/schedule/dto/response/RepetitionPatternResponse.java
  src/main/java/com/sillim/recordit/schedule/repository/RepetitionPatternRepository.java
  src/main/java/com/sillim/recordit/schedule/service/RepetitionPatternService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleGroupService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
  src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/sillim/recordit/schedule/domain/RepetitionPatternTest.java
  src/test/java/com/sillim/recordit/schedule/domain/ScheduleTest.java
  src/test/java/com/sillim/recordit/schedule/service/RepetitionPatternServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleGroupServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
Labels: feature

#59 Release schedule 병합
  src/main/java/com/sillim/recordit/calendar/domain/vo/CalendarTitle.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
  src/main/java/com/sillim/recordit/schedule/domain/RepetitionPattern.java
  src/main/java/com/sillim/recordit/schedule/domain/Schedule.java
  src/main/java/com/sillim/recordit/schedule/domain/ScheduleGroup.java
  src/main/java/com/sillim/recordit/schedule/domain/WeekNumber.java
  src/main/java/com/sillim/recordit/schedule/domain/Weekday.java
  src/main/java/com/sillim/recordit/schedule/domain/vo/Location.java
  src/main/java/com/sillim/recordit/schedule/domain/vo/MonthOfYear.java
  src/main/java/com/sillim/recordit/schedule/domain/vo/ScheduleDescription.java
  src/main/java/com/sillim/recordit/schedule/domain/vo/ScheduleTitle.java
  src/main/java/com/sillim/recordit/schedule/domain/vo/WeekdayBit.java
  src/main/java/com/sillim/recordit/schedule/dto/request/RepetitionAddRequest.java
  src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
  src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
  src/main/java/com/sillim/recordit/schedule/dto/response/MonthScheduleResponse.java
  src/main/java/com/sillim/recordit/schedule/dto/response/RepeatedWeekday.java
  src/main/java/com/sillim/recordit/schedule/dto/response/RepetitionPatternResponse.java
  src/main/java/com/sillim/recordit/schedule/repository/RepetitionPatternRepository.java
  src/main/java/com/sillim/recordit/schedule/service/RepetitionPatternService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleGroupService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
  src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/sillim/recordit/schedule/domain/RepetitionPatternTest.java
  src/test/java/com/sillim/recordit/schedule/domain/ScheduleTest.java
  src/test/java/com/sillim/recordit/schedule/service/RepetitionPatternServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleGroupServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
Labels: feature

#61 🔧 chore[#60]: 배포파일 구성
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  Dockerfile
  appspec.yml
  deploy/deploy.sh
  docker-compose.yml
  src/main/resources/application-prod.yml
Labels: infra

#63 ✨ feature[#51]: 월별 캘린더 일정 조회 기능 구현
  build.gradle
  src/main/java/com/sillim/recordit/global/querydsl/QuerydslRepositorySupport.java
  src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
  src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
  src/main/java/com/sillim/recordit/schedule/repository/ScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
  src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/sillim/recordit/schedule/domain/ScheduleTest.java
  src/test/java/com/sillim/recordit/schedule/fixture/ScheduleFixture.java
  src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
Labels: feature

#65 Release schedule merged main
  build.gradle
  src/main/java/com/sillim/recordit/global/querydsl/QuerydslRepositorySupport.java
  src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
  src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
  src/main/java/com/sillim/recordit/schedule/repository/ScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
  src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/sillim/recordit/schedule/domain/ScheduleTest.java
  src/test/java/com/sillim/recordit/schedule/fixture/ScheduleFixture.java
  src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
Labels: feature

#67 ✨ feature[#66]: 캘린더 조회 기능 구현
  src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
  src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
  src/main/java/com/sillim/recordit/calendar/dto/response/CalendarResponse.java
  src/main/java/com/sillim/recordit/calendar/repository/CalendarRepository.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarService.java
  src/main/java/com/sillim/recordit/config/security/authenticate/CurrentMember.java
  src/main/java/com/sillim/recordit/member/domain/AuthorizedUser.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
Labels: feature

#69 ✨ feature[#68]: 캘린더 추가 기능 구현
  src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
  src/main/java/com/sillim/recordit/calendar/dto/request/CalendarAddRequest.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarService.java
  src/main/java/com/sillim/recordit/global/validation/common/ColorHexValid.java
  src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
  src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarServiceTest.java
Labels: feature

#71 ✨ feature[#70]: 캘린더 삭제 기능 구현
  src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
  src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarService.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/exception/calendar/InvalidCalendarException.java
  src/main/java/com/sillim/recordit/member/domain/Member.java
  src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarServiceTest.java
Labels: feature

#72 Release calendar merge to main
  src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
  src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
  src/main/java/com/sillim/recordit/calendar/dto/request/CalendarAddRequest.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarService.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/exception/calendar/InvalidCalendarException.java
  src/main/java/com/sillim/recordit/global/validation/common/ColorHexValid.java
  src/main/java/com/sillim/recordit/member/domain/Member.java
  src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
  src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarServiceTest.java
Labels: feature

#74 ✨ feature[#73]: monthscheduleresponse에 title 필드 추가
  src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
  src/main/java/com/sillim/recordit/schedule/dto/response/MonthScheduleResponse.java
Labels: feature

#77 🚑️ hotfix[#76]: 일정 시각 저장 시 0초가 아닌 현재 초가 저장되는 현상 수정
  src/main/java/com/sillim/recordit/schedule/domain/vo/ScheduleDuration.java
Labels: hotfix, fix

#79 ✨ feature[#78]: 회원가입 시 기본 캘린더가 생성되는 기능 구현
  src/main/java/com/sillim/recordit/calendar/dto/request/CalendarAddRequest.java
  src/main/java/com/sillim/recordit/member/service/SignupService.java
  src/test/java/com/sillim/recordit/member/service/SignupServiceTest.java
Labels: feature

#80 🚑️ hotfix[#76]: 시, 분은 원래대로 저장되도록 수정
  src/main/java/com/sillim/recordit/schedule/domain/vo/ScheduleDuration.java
Labels: hotfix

#82 ✨ feature[#81]: 월별 일정 조회 시 시작일의 오름차순으로 조회되도록 수정
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
  src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
Labels: feature

#83 Release schedule
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
  src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
Labels: feature

#86 ✨ feature[#81]: 시작 날짜의 오름차순, 끝 날짜의 내림차순으로 조회되도록 구현
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
Labels: feature

#87 Release schedule
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
Labels: feature
