Repository let-s-record-it/Server, pull requests merged in 2025-02, with the labels that each got.

#227 Feature 226 OAuth2 로그인 기능 구현
  build.gradle
  src/main/java/com/sillim/recordit/config/security/SecurityConfig.java
  src/main/java/com/sillim/recordit/config/security/jwt/JwtProvider.java
  src/main/java/com/sillim/recordit/config/security/oauth2/DefaultUserService.java
  src/main/java/com/sillim/recordit/config/security/oauth2/LoginMember.java
  src/main/java/com/sillim/recordit/config/security/oauth2/OAuth2Request.java
  src/main/java/com/sillim/recordit/config/security/oauth2/OAuth2SuccessHandler.java
  src/main/java/com/sillim/recordit/config/security/oauth2/mapper/AttributeMapper.java
  src/main/java/com/sillim/recordit/config/security/oauth2/mapper/AttributeMapperFactory.java
  src/main/java/com/sillim/recordit/config/security/oauth2/mapper/GoogleAttributeMapper.java
  src/main/java/com/sillim/recordit/config/security/oauth2/mapper/KakaoAttributeMapper.java
  src/main/java/com/sillim/recordit/config/security/oauth2/mapper/LoginMemberMapper.java
  src/main/java/com/sillim/recordit/config/security/oauth2/mapper/NaverAttributeMapper.java
  src/main/java/com/sillim/recordit/member/controller/LoginController.java
  src/main/java/com/sillim/recordit/member/dto/request/WebLoginRequest.java
  src/main/java/com/sillim/recordit/member/service/LoginService.java
  src/main/java/com/sillim/recordit/member/service/MemberQueryService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/resources/application-test.yml
Labels: feature

#228 Feature 225 캘린더 멤버 초대 기능 구현
  src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
  src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
  src/main/java/com/sillim/recordit/calendar/domain/CalendarMember.java
  src/main/java/com/sillim/recordit/calendar/dto/request/JoinInCalendarRequest.java
  src/main/java/com/sillim/recordit/calendar/dto/response/CalendarMemberResponse.java
  src/main/java/com/sillim/recordit/calendar/repository/CalendarMemberRepository.java
  src/main/java/com/sillim/recordit/calendar/repository/CustomCalendarMemberRepository.java
  src/main/java/com/sillim/recordit/calendar/repository/CustomCalendarMemberRepositoryImpl.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarCommandService.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarMemberService.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarQueryService.java
  src/main/java/com/sillim/recordit/calendar/service/JoinCalendarService.java
  src/main/java/com/sillim/recordit/config/security/SecurityConfig.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/invite/controller/InviteController.java
  src/main/java/com/sillim/recordit/invite/domain/InviteLink.java
  src/main/java/com/sillim/recordit/invite/dto/response/InviteInfoResponse.java
  src/main/java/com/sillim/recordit/invite/dto/response/InviteLinkResponse.java
  src/main/java/com/sillim/recordit/invite/repository/CustomInviteLinkRepository.java
  src/main/java/com/sillim/recordit/invite/repository/CustomInviteLinkRepositoryImpl.java
  src/main/java/com/sillim/recordit/invite/repository/InviteLinkRepository.java
  src/main/java/com/sillim/recordit/invite/service/InviteService.java
  src/main/java/com/sillim/recordit/member/dto/response/ProfileResponse.java
  src/main/java/com/sillim/recordit/member/service/SignupService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
  src/main/java/com/sillim/recordit/task/service/TaskCommandService.java
  src/main/java/com/sillim/recordit/task/service/TaskQueryService.java
  src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
  src/test/java/com/sillim/recordit/calendar/repository/CustomCalendarMemberRepositoryImplTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarCommandServiceTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarMemberServiceTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarQueryServiceTest.java
  src/test/java/com/sillim/recordit/feed/repository/CustomFeedCommentRepositoryTest.java
  src/test/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryTest.java
  src/test/java/com/sillim/recordit/invite/service/InviteServiceTest.java
  src/test/java/com/sillim/recordit/member/service/SignupServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
  src/test/java/com/sillim/recordit/task/service/TaskCommandServiceTest.java
  src/test/java/com/sillim/recordit/task/service/TaskQueryServiceTest.java
Labels: feature

#231 Feature 230 캘린더 주인이 아니여도 멤버 목록이 보이도록 수정
  src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarMemberService.java
  src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarMemberServiceTest.java
Labels: fix

#234 Feature 232 캘린더 수정 기능 구현
  src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
  src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
  src/main/java/com/sillim/recordit/calendar/dto/request/CalendarModifyRequest.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarCommandService.java
  src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarCommandServiceTest.java
Labels: feature

#235 fix[#233]: 캘린더 생성 시 캘린더 멤버에 들어가지 않는 문제 수정
  src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
  src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
Labels: fix

#236 develop merge into main
  src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
  src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
  src/main/java/com/sillim/recordit/calendar/dto/request/CalendarModifyRequest.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarCommandService.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarMemberService.java
  src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarCommandServiceTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarMemberServiceTest.java
Labels: feature

#238 Feature 237 캘린더 멤버 삭제 기능 구현
  src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
  src/main/java/com/sillim/recordit/calendar/repository/CalendarMemberRepository.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarMemberService.java
  src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarMemberServiceTest.java
Labels: feature

#240 Feature 239 캘린더, 일정 색상을 각각 카테고리로 분리
  src/main/java/com/sillim/recordit/calendar/controller/CalendarCategoryController.java
  src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
  src/main/java/com/sillim/recordit/calendar/domain/CalendarCategory.java
  src/main/java/com/sillim/recordit/calendar/domain/vo/CalendarCategoryName.java
  src/main/java/com/sillim/recordit/calendar/dto/request/CalendarAddRequest.java
  src/main/java/com/sillim/recordit/calendar/dto/request/CalendarCategoryAddRequest.java
  src/main/java/com/sillim/recordit/calendar/dto/request/CalendarCategoryModifyRequest.java
  src/main/java/com/sillim/recordit/calendar/dto/request/CalendarModifyRequest.java
  src/main/java/com/sillim/recordit/calendar/dto/response/CalendarCategoryListResponse.java
  src/main/java/com/sillim/recordit/calendar/repository/CalendarCategoryRepository.java
  src/main/java/com/sillim/recordit/calendar/repository/CalendarRepository.java
  src/main/java/com/sillim/recordit/calendar/repository/CustomCalendarMemberRepositoryImpl.java
  src/main/java/com/sillim/recordit/calendar/repository/CustomCalendarRepository.java
  src/main/java/com/sillim/recordit/calendar/repository/CustomCalendarRepositoryImpl.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarCategoryService.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarCommandService.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarQueryService.java
  src/main/java/com/sillim/recordit/category/controller/ScheduleCategoryController.java
  src/main/java/com/sillim/recordit/category/domain/ScheduleCategory.java
  src/main/java/com/sillim/recordit/category/domain/vo/ScheduleCategoryName.java
  src/main/java/com/sillim/recordit/category/dto/request/ScheduleCategoryAddRequest.java
  src/main/java/com/sillim/recordit/category/dto/request/ScheduleCategoryModifyRequest.java
  src/main/java/com/sillim/recordit/category/dto/response/ScheduleCategoryListResponse.java
  src/main/java/com/sillim/recordit/category/repository/ScheduleCategoryRepository.java
  src/main/java/com/sillim/recordit/category/service/ScheduleCategoryService.java
  src/main/java/com/sillim/recordit/enums/color/DefaultColor.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/exception/common/InvalidCategoryNameException.java
  src/main/java/com/sillim/recordit/member/service/SignupService.java
  src/main/java/com/sillim/recordit/schedule/domain/Schedule.java
  src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleAddRequest.java
  src/main/java/com/sillim/recordit/schedule/dto/request/ScheduleModifyRequest.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/test/java/com/sillim/recordit/calendar/controller/CalendarCategoryControllerTest.java
  src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
  src/test/java/com/sillim/recordit/calendar/domain/vo/CalendarCategoryNameTest.java
  src/test/java/com/sillim/recordit/calendar/fixture/CalendarCategoryFixture.java
  src/test/java/com/sillim/recordit/calendar/fixture/CalendarFixture.java
  src/test/java/com/sillim/recordit/calendar/repository/CustomCalendarMemberRepositoryImplTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarCategoryServiceTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarCommandServiceTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarMemberServiceTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarQueryServiceTest.java
  src/test/java/com/sillim/recordit/category/domain/vo/ScheduleCategoryNameTest.java
  src/test/java/com/sillim/recordit/category/fixture/ScheduleCategoryFixture.java
  src/test/java/com/sillim/recordit/category/service/ScheduleCategoryServiceTest.java
  src/test/java/com/sillim/recordit/invite/service/InviteServiceTest.java
  src/test/java/com/sillim/recordit/member/service/SignupServiceTest.java
  src/test/java/com/sillim/recordit/schedule/controller/ScheduleControllerTest.java
  src/test/java/com/sillim/recordit/schedule/domain/ScheduleTest.java
  src/test/java/com/sillim/recordit/schedule/fixture/ScheduleFixture.java
  src/test/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleQueryServiceTest.java
  src/test/java/com/sillim/recordit/task/controller/TaskControllerTest.java
  src/test/java/com/sillim/recordit/task/domain/TaskTest.java
  src/test/java/com/sillim/recordit/task/repository/CustomTaskRepositoryTest.java
  src/test/java/com/sillim/recordit/task/repository/TaskRepositoryTest.java
  src/test/java/com/sillim/recordit/task/service/TaskCommandServiceTest.java
Labels: feature, refactor

#243 hotfix[#242]: ClassMember가 중복 저장되는 문제 해결
  src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
Labels: hotfix

#244 develop merge into main
  src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
Labels: feature

#246 hotfix[#245]: 캘린더 삭제 시 캘린더 멤버 연관관계로 인해 삭제되지 않는 현상 수정
  src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
  src/main/java/com/sillim/recordit/calendar/domain/CalendarMember.java
  src/test/java/com/sillim/recordit/calendar/domain/CalendarMemberTest.java
Labels: hotfix

#249 Feature 248 일정 카테고리 삭제 시 남아있는 일정이 기본 카테고리로 적용되도록 수정
  src/main/java/com/sillim/recordit/calendar/domain/CalendarCategory.java
  src/main/java/com/sillim/recordit/calendar/dto/response/CalendarCategoryListResponse.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarCategoryService.java
  src/main/java/com/sillim/recordit/category/controller/ScheduleCategoryController.java
  src/main/java/com/sillim/recordit/category/domain/ScheduleCategory.java
  src/main/java/com/sillim/recordit/category/dto/response/ScheduleCategoryListResponse.java
  src/main/java/com/sillim/recordit/category/repository/ScheduleCategoryRepository.java
  src/main/java/com/sillim/recordit/category/service/ScheduleCategoryCommandService.java
  src/main/java/com/sillim/recordit/category/service/ScheduleCategoryQueryService.java
  src/main/java/com/sillim/recordit/enums/color/DefaultColor.java
  src/main/java/com/sillim/recordit/enums/color/InitialColor.java
  src/main/java/com/sillim/recordit/member/service/SignupService.java
  src/main/java/com/sillim/recordit/schedule/repository/ScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/test/java/com/sillim/recordit/calendar/fixture/CalendarCategoryFixture.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarCategoryServiceTest.java
  src/test/java/com/sillim/recordit/category/fixture/ScheduleCategoryFixture.java
  src/test/java/com/sillim/recordit/category/service/ScheduleCategoryCommandServiceTest.java
  src/test/java/com/sillim/recordit/category/service/ScheduleCategoryQueryServiceTest.java
  src/test/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryTest.java
  src/test/java/com/sillim/recordit/member/service/SignupServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
Labels: fix

#250 develop merge into main
  src/main/java/com/sillim/recordit/calendar/domain/CalendarCategory.java
  src/main/java/com/sillim/recordit/calendar/dto/response/CalendarCategoryListResponse.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarCategoryService.java
  src/main/java/com/sillim/recordit/category/controller/ScheduleCategoryController.java
  src/main/java/com/sillim/recordit/category/domain/ScheduleCategory.java
  src/main/java/com/sillim/recordit/category/dto/response/ScheduleCategoryListResponse.java
  src/main/java/com/sillim/recordit/category/repository/ScheduleCategoryRepository.java
  src/main/java/com/sillim/recordit/category/service/ScheduleCategoryCommandService.java
  src/main/java/com/sillim/recordit/category/service/ScheduleCategoryQueryService.java
  src/main/java/com/sillim/recordit/enums/color/DefaultColor.java
  src/main/java/com/sillim/recordit/enums/color/InitialColor.java
  src/main/java/com/sillim/recordit/member/service/SignupService.java
  src/main/java/com/sillim/recordit/schedule/repository/ScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/test/java/com/sillim/recordit/calendar/fixture/CalendarCategoryFixture.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarCategoryServiceTest.java
  src/test/java/com/sillim/recordit/category/fixture/ScheduleCategoryFixture.java
  src/test/java/com/sillim/recordit/category/service/ScheduleCategoryCommandServiceTest.java
  src/test/java/com/sillim/recordit/category/service/ScheduleCategoryQueryServiceTest.java
  src/test/java/com/sillim/recordit/feed/repository/CustomFeedRepositoryTest.java
  src/test/java/com/sillim/recordit/member/service/SignupServiceTest.java
  src/test/java/com/sillim/recordit/schedule/service/ScheduleCommandServiceTest.java
Labels: feature

#252 Feature 251 캘린더, 카테고리 soft delete 적용
  src/main/java/com/sillim/recordit/calendar/controller/CalendarCategoryController.java
  src/main/java/com/sillim/recordit/calendar/controller/CalendarController.java
  src/main/java/com/sillim/recordit/calendar/domain/Calendar.java
  src/main/java/com/sillim/recordit/calendar/domain/CalendarCategory.java
  src/main/java/com/sillim/recordit/calendar/domain/CalendarMember.java
  src/main/java/com/sillim/recordit/calendar/repository/CalendarCategoryRepository.java
  src/main/java/com/sillim/recordit/calendar/repository/CalendarMemberRepository.java
  src/main/java/com/sillim/recordit/calendar/repository/CustomCalendarMemberRepositoryImpl.java
  src/main/java/com/sillim/recordit/calendar/repository/CustomCalendarRepositoryImpl.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarCategoryService.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarCommandService.java
  src/main/java/com/sillim/recordit/calendar/service/CalendarMemberService.java
  src/main/java/com/sillim/recordit/calendar/service/JoinCalendarService.java
  src/main/java/com/sillim/recordit/category/domain/ScheduleCategory.java
  src/main/java/com/sillim/recordit/category/repository/ScheduleCategoryRepository.java
  src/main/java/com/sillim/recordit/category/service/ScheduleCategoryCommandService.java
  src/main/java/com/sillim/recordit/category/service/ScheduleCategoryQueryService.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/schedule/repository/ScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleCommandService.java
  src/test/java/com/sillim/recordit/calendar/controller/CalendarControllerTest.java
  src/test/java/com/sillim/recordit/calendar/domain/CalendarMemberTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarCategoryServiceTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarCommandServiceTest.java
  src/test/java/com/sillim/recordit/calendar/service/CalendarMemberServiceTest.java
  src/test/java/com/sillim/recordit/calendar/service/JoinCalendarServiceTest.java
  src/test/java/com/sillim/recordit/category/service/ScheduleCategoryQueryServiceTest.java
Labels: feature, refactor

#254 feature[#253]: 일정 검색 기능 구현
  src/main/java/com/sillim/recordit/schedule/controller/ScheduleController.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepository.java
  src/main/java/com/sillim/recordit/schedule/repository/CustomScheduleRepositoryImpl.java
  src/main/java/com/sillim/recordit/schedule/service/ScheduleQueryService.java
Labels: feature

#256 fix[#255]: 주 목표 조회 시 주차에 맞게 조회되도록 수정
  src/main/java/com/sillim/recordit/goal/domain/vo/WeeklyGoalPeriod.java
  src/main/java/com/sillim/recordit/goal/repository/CustomWeeklyGoalRepositoryImpl.java
  src/test/java/com/sillim/recordit/goal/domain/vo/WeeklyGoalPeriodTest.java
  src/test/java/com/sillim/recordit/goal/repository/WeeklyGoalRepositoryTest.java
Labels: fix

#258 Feature 257 할 일, 목표를 색상 카테고리와 연동
  src/main/java/com/sillim/recordit/category/service/ScheduleCategoryCommandService.java
  src/main/java/com/sillim/recordit/goal/domain/MonthlyGoal.java
  src/main/java/com/sillim/recordit/goal/domain/WeeklyGoal.java
  src/main/java/com/sillim/recordit/goal/dto/request/MonthlyGoalUpdateRequest.java
  src/main/java/com/sillim/recordit/goal/dto/request/WeeklyGoalUpdateRequest.java
  src/main/java/com/sillim/recordit/goal/dto/response/MonthlyGoalDetailsResponse.java
  src/main/java/com/sillim/recordit/goal/dto/response/MonthlyGoalListResponse.java
  src/main/java/com/sillim/recordit/goal/dto/response/WeeklyGoalDetailsResponse.java
  src/main/java/com/sillim/recordit/goal/dto/response/WeeklyGoalResponse.java
  src/main/java/com/sillim/recordit/goal/repository/CustomMonthlyGoalRepository.java
  src/main/java/com/sillim/recordit/goal/repository/CustomMonthlyGoalRepositoryImpl.java
  src/main/java/com/sillim/recordit/goal/repository/CustomWeeklyGoalRepositoryImpl.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalQueryService.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
  src/main/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateService.java
  src/main/java/com/sillim/recordit/schedule/dto/response/DayScheduleResponse.java
  src/main/java/com/sillim/recordit/task/controller/TaskController.java
  src/main/java/com/sillim/recordit/task/domain/Task.java
  src/main/java/com/sillim/recordit/task/dto/request/TaskAddRequest.java
  src/main/java/com/sillim/recordit/task/dto/request/TaskUpdateRequest.java
  src/main/java/com/sillim/recordit/task/dto/response/TaskDetailsResponse.java
  src/main/java/com/sillim/recordit/task/dto/response/TaskResponse.java
  src/main/java/com/sillim/recordit/task/repository/CustomTaskRepository.java
  src/main/java/com/sillim/recordit/task/repository/CustomTaskRepositoryImpl.java
  src/main/java/com/sillim/recordit/task/repository/TaskRepository.java
  src/main/java/com/sillim/recordit/task/service/TaskCommandService.java
  src/main/java/com/sillim/recordit/task/service/TaskQueryService.java
  src/test/java/com/sillim/recordit/category/service/ScheduleCategoryCommandServiceTest.java
  src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/controller/WeeklyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/domain/MonthlyGoalTest.java
  src/test/java/com/sillim/recordit/goal/domain/WeeklyGoalTest.java
  src/test/java/com/sillim/recordit/goal/dto/request/MonthlyUpdateRequestTest.java
  src/test/java/com/sillim/recordit/goal/fixture/MonthlyGoalFixture.java
  src/test/java/com/sillim/recordit/goal/fixture/WeeklyGoalFixture.java
  src/test/java/com/sillim/recordit/goal/repository/MonthlyGoalRepositoryTest.java
  src/test/java/com/sillim/recordit/goal/repository/WeeklyGoalRepositoryTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalQueryServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/WeeklyGoalQueryServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateServiceTest.java
  src/test/java/com/sillim/recordit/task/controller/TaskControllerTest.java
  src/test/java/com/sillim/recordit/task/domain/TaskTest.java
  src/test/java/com/sillim/recordit/task/fixture/TaskFixture.java
  src/test/java/com/sillim/recordit/task/repository/CustomTaskRepositoryTest.java
  src/test/java/com/sillim/recordit/task/repository/TaskRepositoryTest.java
  src/test/java/com/sillim/recordit/task/service/TaskCommandServiceTest.java
  src/test/java/com/sillim/recordit/task/service/TaskQueryServiceTest.java
Labels: feature

#198 Feature 197: 할 일 연관 목표 연결 기능 구현
  src/main/java/com/sillim/recordit/goal/controller/GoalController.java
  src/main/java/com/sillim/recordit/goal/dto/response/GoalListResponse.java
  src/main/java/com/sillim/recordit/goal/dto/response/GoalResponse.java
  src/main/java/com/sillim/recordit/task/service/TaskGroupService.java
  src/test/java/com/sillim/recordit/goal/controller/GoalControllerTest.java
  src/test/java/com/sillim/recordit/task/service/TaskGroupServiceTest.java
Labels: feature

#196 Feature 195: 주 목표 연관 목표 연결/연결 해제 기능 구현
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/java/com/sillim/recordit/global/exception/goal/InvalidWeeklyGoalException.java
  src/main/java/com/sillim/recordit/goal/controller/GoalController.java
  src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
  src/main/java/com/sillim/recordit/goal/controller/WeeklyGoalController.java
  src/main/java/com/sillim/recordit/goal/domain/WeeklyGoal.java
  src/main/java/com/sillim/recordit/goal/dto/response/GoalListResponse.java
  src/main/java/com/sillim/recordit/goal/dto/response/GoalResponse.java
  src/main/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateService.java
  src/main/java/com/sillim/recordit/task/service/TaskGroupService.java
  src/test/java/com/sillim/recordit/goal/controller/GoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/controller/WeeklyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/domain/WeeklyGoalTest.java
  src/test/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateServiceTest.java
  src/test/java/com/sillim/recordit/task/service/TaskGroupServiceTest.java
Labels: feature

#260 Feature 259 월 목표 캘린더 연결
  src/main/java/com/sillim/recordit/goal/controller/GoalController.java
  src/main/java/com/sillim/recordit/goal/controller/MonthlyGoalController.java
  src/main/java/com/sillim/recordit/goal/controller/WeeklyGoalController.java
  src/main/java/com/sillim/recordit/goal/domain/MonthlyGoal.java
  src/main/java/com/sillim/recordit/goal/domain/WeeklyGoal.java
  src/main/java/com/sillim/recordit/goal/dto/request/MonthlyGoalUpdateRequest.java
  src/main/java/com/sillim/recordit/goal/dto/request/WeeklyGoalUpdateRequest.java
  src/main/java/com/sillim/recordit/goal/dto/response/MonthlyGoalDetailsResponse.java
  src/main/java/com/sillim/recordit/goal/dto/response/MonthlyGoalListResponse.java
  src/main/java/com/sillim/recordit/goal/dto/response/WeeklyGoalDetailsResponse.java
  src/main/java/com/sillim/recordit/goal/dto/response/WeeklyGoalResponse.java
  src/main/java/com/sillim/recordit/goal/repository/CustomMonthlyGoalRepository.java
  src/main/java/com/sillim/recordit/goal/repository/CustomMonthlyGoalRepositoryImpl.java
  src/main/java/com/sillim/recordit/goal/repository/CustomWeeklyGoalRepository.java
  src/main/java/com/sillim/recordit/goal/repository/CustomWeeklyGoalRepositoryImpl.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalQueryService.java
  src/main/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateService.java
  src/main/java/com/sillim/recordit/goal/service/WeeklyGoalQueryService.java
  src/main/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateService.java
  src/test/java/com/sillim/recordit/goal/controller/GoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/controller/MonthlyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/controller/WeeklyGoalControllerTest.java
  src/test/java/com/sillim/recordit/goal/domain/MonthlyGoalTest.java
  src/test/java/com/sillim/recordit/goal/domain/WeeklyGoalTest.java
  src/test/java/com/sillim/recordit/goal/dto/request/MonthlyUpdateRequestTest.java
  src/test/java/com/sillim/recordit/goal/fixture/MonthlyGoalFixture.java
  src/test/java/com/sillim/recordit/goal/fixture/WeeklyGoalFixture.java
  src/test/java/com/sillim/recordit/goal/repository/MonthlyGoalRepositoryTest.java
  src/test/java/com/sillim/recordit/goal/repository/WeeklyGoalRepositoryTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalQueryServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/MonthlyGoalUpdateServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/WeeklyGoalQueryServiceTest.java
  src/test/java/com/sillim/recordit/goal/service/WeeklyGoalUpdateServiceTest.java
  src/test/java/com/sillim/recordit/task/controller/TaskControllerTest.java
Labels: feature
