Repository let-s-record-it/Server, pull requests merged in 2025-09, with the labels that each got.

#305 chore[#302]: prod neo4j env 추가
  src/main/resources/application-prod.yml
Labels: fix

#324 배포 워크플로에 애플리케이션 헬스체크 스크립트 추가
  .github/workflows/deploy.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: infra

#333 [Feature] JWT Token 검증 API 엔드포인트 추가
  src/main/java/com/sillim/recordit/config/neo4j/LocalNeo4jInitializer.java
  src/main/java/com/sillim/recordit/member/controller/LoginController.java
Labels: feature

#319 feature[#318]: 특정 API에 처리율 제한 적용
  build.gradle
  src/main/java/com/sillim/recordit/config/cache/RedisConfig.java
  src/main/java/com/sillim/recordit/config/filter/ApiThrottlingFilter.java
  src/main/java/com/sillim/recordit/config/filter/LimitApi.java
  src/main/java/com/sillim/recordit/config/ratelimiter/RateLimiterConfig.java
  src/main/java/com/sillim/recordit/global/exception/ErrorCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/sillim/recordit/config/filter/ApiThrottlingFilterTest.java
  src/test/java/com/sillim/recordit/support/restdocs/RestDocsTest.java
Labels: feature

#335 feature[#332]: 좋아요 알림 기능 구현
  src/main/java/com/sillim/recordit/feed/service/FeedLikeService.java
  src/main/java/com/sillim/recordit/pushalarm/dto/AlarmType.java
  src/main/java/com/sillim/recordit/pushalarm/dto/PushMessage.java
  src/test/java/com/sillim/recordit/feed/service/FeedLikeServiceTest.java
Labels: feature
